

services:
  backend:
    build:
      context: /Trip_Planner
      dockerfile: Dockerfile
    image: trip_planner
    ports:
      - "8080:8080"
    networks:
      - trip_network 
    container_name: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080 
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=trip_planner;Username=postgres;Password=Bakir123420
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Bakir123420
      - POSTGRES_DB=trip_planner
    ports:
      - "5433:5432"
    networks:
      - trip_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
    trip_network:
        driver: bridge    
volumes:
  postgres_data:
